upstream django {
    server test:8005
}

server {
    listen 80;
    server_name 165.227.43.168;

    location = /favicon.ico { access_log off; log_not_found off; }
#     location /static/ {
#         root /home/sammy/myprojectdir;
#     }

    location / {
        include proxy_params;
        proxy_pass http://django;
    }
}